//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Court
    {
        public int CourtId { get; set; }
        public string CourtCode { get; set; }
        public string CourtName { get; set; }
        public string CourtRemarks { get; set; }
        public Nullable<int> CourtStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> CourtDateTimeStamp { get; set; }
        public string UserName { get; set; }
        public string TerminalName { get; set; }
    }
}
