//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LawFile
    {
        public int FileId { get; set; }
        public string FileCode { get; set; }
        public string FileTitle { get; set; }
        public string FileDescription { get; set; }
        public string FilePath { get; set; }
        public string FileAbstract { get; set; }
        public Nullable<int> JudgeId { get; set; }
        public string FileRemarks { get; set; }
        public Nullable<int> CourtId { get; set; }
        public string FileYear { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> FileDateTimeStamp { get; set; }
        public string TerminalName { get; set; }
    }
}
