//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionId { get; set; }
        public string SectionCode { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> LawId { get; set; }
        public Nullable<int> SectionRefId { get; set; }
        public Nullable<int> SectionStatus { get; set; }
        public string UserId { get; set; }
        public string SectionRemarks { get; set; }
        public Nullable<System.DateTime> SectionDateTimeStamp { get; set; }
        public string TerminalName { get; set; }
    }
}
