//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSearch.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Judge
    {
        public int JudgeId { get; set; }
        public string JudgeCode { get; set; }
        public string JudgeName { get; set; }
        public string JudgeRemarks { get; set; }
        public Nullable<int> JudgeStatus { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> DateTimeStamp { get; set; }
        public string TerminalName { get; set; }
    }
}
